### PR TITLE
Improve startup log messages

### PR DESCRIPTION
**Pull request by ioguix**
When the getkey_script file is missing, previous startup error message was wrongly showing "Permission denied for %s". This shows a relevant error message with addition of some details and hints.

The patch also improves other startup error/log messages so they repect the PostgreSQL log format if stderr is collected.

### CODE REVIEW

**Review by michelp — APPROVED** [review]
Looks great, thank you!

**Comment by michelp** [comment]
Hmm github won't run the tests it says "Expected-- Waiting for status to be reported" that's... unclear.  Anyway, googling is giving me vague answers about personal access tokens, any thoughts on what I'm waiting to be reported to from what?

**Comment by ioguix** [comment]
> Hmm github won't run the tests it says "Expected-- Waiting for status to be reported" that's... unclear. Anyway, googling is giving me vague answers about personal access tokens, any thoughts on what I'm waiting to be reported to from what?

I have absolutely no clue... First time I'm seeing this.

I rebased the branch on current HEAD by the way.

**Comment by ioguix** [comment]
Maybe you can somehow manually trigger the `tests` workflow?

**Pull request merged**
