### PR TITLE
Add tap tests on pgsodium objects schema

### PR DESCRIPTION
**Pull request by ioguix**
This adds tap tests on the pgsodium extension itself. This should help enforce some sanity rules about ownership, privileges, existing objects, etc.

This is currently a draft as:
- it has been generated by the `pgsodium_tapgen.pl` perl script and needs some detailed review.
- it still requires some more tests

The generation script itself is included in this PR for information only. The objective is to edit the `pgsodium_schema.sql` test script bu hand.

### CODE REVIEW

**Comment by ioguix** [comment]
Note that the tests are currently failing because of #68

**Comment by ioguix** [comment]
Hi,

There's currently 1729 tests including the ones from commit f64f2cf.

We could add some more tests around indexes and constraints on table `keys`.

From here, I'll need some serious review, the next steps would be to:
* check all owners, privs, strictiness, security definers and so on
* fix them in the tests (turns the tests red)
* fix them in the code (turns the tests green)

Regards,

**Review by michelp — APPROVED** [review]
This is huge!  Thanks so much for this work.  I went through it as much as I could, and I'm happy with "freezing" the interface contract to this test spec going forward.  As the package evolves we'll be careful to make sure the contract is honored or making very explicit major version releases that might break things.

**Comment by ioguix** [comment]
Thank you!

**Pull request merged**
